version: '2.2'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
      - PGDATA=\pyforge-3\pgdata
    command:
      - "postgres"
      - "-rm"

